site_name: Systemsikkerhed
site_description: 'Mine noter til Systemsikkerhed'
site_author: 'Kresten Jacobsen'
site_url: 'https://krejac.github.io/kea-sys-sec'

# Copyright
copyright: 'Copyleft - Kresten Jacobsen - <em>Kopier, skriv af, gør hvad du vil - og meld gerne fejl tilbage. :)</em>'

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'deep orange'
    accent: 'orange'
  language: 'da'

# Repository
repo_name: krejac/kea-sys-sec
repo_url: https://github.com/krejac/kea-sys-sec

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - footnotes
