site_name: Systemsikkerhed

theme:
  name: 'material'
  palette:
    primary: 'deep orange'
    accent: 'orange'
  language: 'da'

# Repository
repo_name: krejac/kea-sys-sec
repo_url: https://github.com/krejac/kea-sys-sec
edit_uri: ""

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - footnotes
