site_name: Systemsikkerhed



theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'blue'
  language: 'da'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - footnotes
